# Generated by Django 5.0.6 on 2025-05-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_myuser_first_name_remove_myuser_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='username',
        ),
    ]
