# Generated by Django 5.0.6 on 2025-05-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
    ]
